config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :tournament do
    get 'new_bet'
    post 'place_bet'
  end

  root to: 'tournaments#show'

end

app/models/bet.rb
class Bet < ActiveRecord::Base
  attr_accessible :team_id, :type_of_bet

  belongs_to :user
  belongs_to :team
  enum type_of_bet: [:team_a, :team_b, :team_c, :team_d, :scores_the_most, :gets_the_most]
  validates_presence_of :team
  def self.type_for(step)
	self.type_of_bets.invert[step]
  end

end

app/models/match.rb
class Match < ActiveRecord::Base
	require './lib/score_calculator.rb'

	belongs_to :team_a, class_name: "Team", foreign_key: "team_a_id"
	belongs_to :team_b, class_name: "Team", foreign_key: "team_b_id"

	enum round: [:group_round, :eighth_final, :quarter_final, :semi_final, :final]

	attr_accessible :round, :starting_time, :team_a, :team_b

	store_accessor :score, :team_a_score, :team_b_score, :shoot_out

	scope :completed, -> { where("score is not null") }

	after_save { |m| ScoreCalculator.re_calculate_user_scores }

	def teams
		[team_a, team_b]
	end

	def other_team(team)
		team == team_a ? team_b : team_a
	end

	def result_for(team)
		if shoot_out 
			result_for_shoot_out(team)
		elsif draw?
			:draw
		elsif team == winner
			:win
		elsif team == loser
			:lost
		end
	end


	def result_for_shoot_out(team)
		a_score = shoot_out[:team_a_shoot_out_score].to_i
		b_score = shoot_out[:team_b_shoot_out_score].to_i
		winner = a_score > b_score ? team_a : team_b
		team == winner ? :win : :lost
	end

	def winner
		a_score = team_a_score.to_i
		b_score = team_b_score.to_i

		if a_score > b_score
			return team_a
		elsif a_score < b_score
			return team_b
		end
	end

	def loser
		unless winner.nil?
			other_team(winner)
		end 
	end

	def draw?
		team_a_score.to_i == team_b_score.to_i
	end

	def score_of team
		if team == team_a 
			team_a_score.to_i
		elsif team == team_b
			team_b_score.to_i
		end
	end

	def future_match?
		score.nil?
	end
end

app/models/team.rb
class Team < ActiveRecord::Base
	attr_accessible :code, :name, :rank
	has_many :bets

	# has_many :matches_as_team_a, class_name: "Match", foreign_key: "team_a_id"
	# has_many :matches_as_team_b, class_name: "Match", foreign_key: "team_b_id"

	scope :first_rank, -> { where(rank: 1) }
	scope :second_rank, -> { where(rank: 2) }
	scope :third_rank, -> { where(rank: 3) }
	scope :forth_rank, -> { where(rank: 4) }

	def matches
		Match.where("team_a_id = ? OR team_b_id = ?", self.id, self.id)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name

  has_many :bets

  def bet_setup_step
    bets.count
  end

  def placed_full_bet?
  	bets.count == 6
  end

  def name_with_nickname
    "#{first_name.try(:capitalize)} '#{nickname.try(:capitalize)}' #{last_name.try(:capitalize)}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :validate_placed_bet, only: :show 

	def show
      # @next_matches = Match.where("starting_time > ?", Time.now).all
      @next_matches = Match.where("score is null").order('starting_time asc').first(10)
      @past_matches = Match.completed.order('starting_time desc').first(10)
      @teams = Team.all
      @users = User.order('points desc').all
      respond_to do |format|
      	format.html
      	format.js
	  end
	end

	def new_bet
	  @step = current_user.bets.count
	  @teams = team_options
	  @type_of_bet = Bet.type_for(@step)
	  respond_to do |format|
	  	format.html
	  	format.js
	  end
	end

  # ahm..
	def place_bet
	  current_user.bets.create(bet_params)

      respond_to do |format|
      	if current_user.placed_full_bet?
        # format.js{ redirect_to tournament_path }
     	    # redirect_to tournament_path 
          format.js { render :js => "window.location.href = '#{tournament_path}'" }
      	else 
      	  format.js{ redirect_to new_bet_tournament_path}
      	end
      end
	end


  private 

  	def team_options
      case @step
      when 0
      	Team.first_rank
      when 1
      	Team.second_rank
      when 2
      	Team.third_rank
      when 3
      	Team.forth_rank
      else
        Team.all
      end

  	end

  	def validate_placed_bet
  	  if current_user.placed_full_bet? 
  	  	return
  	  else
  	  	redirect_to new_bet_tournament_path 
  	  end
  	end

  	def bet_params
  	  params.require(:bet).permit(:team_id, :type_of_bet)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tournament_helper.rb
module TournamentHelper

	def flag_tag team
		image_tag("flags/#{team.code}.png", class: 'flag')
	end

	def team_name_and_flag(team)	
		content_tag(:div, team.name) + flag_tag(team)
	end	


	def future_match_regular_bet_prospect match
		relevant_bets = current_user.bets.select{ |b| match.teams.include? b.team }
		return if relevant_bets.empty?

		r = relevant_bets.select{ |b| ['team_a', 'team_b', 'team_c', 'team_d'].include? b.type_of_bet }.collect do |b|
			msg_for_future_match match, b
		end
		r.join("<br>")
	end


	def msg_for_future_match match, bet
		bet_team = match.team_a == bet.team ? match.team_a : match.team_b
		r1 = bet_team.rank
		r2 = match.other_team(bet_team).rank

		msg = []
		msg << "You'll win #{ScoreCalculator::SCORES_BY_RANK_VS_RANK[r1][r2][:win]} points if #{bet_team.name.capitalize} wins"

		points_to_be_earned = ScoreCalculator::SCORES_BY_RANK_VS_RANK[r1][r2][:draw]
		if points_to_be_earned != 0
			msg << "#{pluralize(points_to_be_earned, 'point')} if it's a draw"
		end		

		points_to_be_lost = -ScoreCalculator::SCORES_BY_RANK_VS_RANK[r1][r2][:lost]
		if points_to_be_lost != 0
			msg << "you'll lose #{pluralize(points_to_be_lost, 'point')} if #{bet_team.name.capitalize} loses"
		end

		last = msg.pop
		msg.join(', ') + " and #{last}."
	end

	def future_match_custom_bet_prospect match
		relevant_bets = current_user.bets.select{ |b| match.teams.include? b.team }
		return if relevant_bets.empty?

		msg = relevant_bets.collect do |b| 
			if b.type_of_bet == 'scores_the_most'
				"You'll win half a point for every goal #{b.team.name.capitalize} scores."
			elsif b.type_of_bet == 'gets_the_most'
				"You'll win half a point for every goal scored to #{b.team.name.capitalize}."
			end
		end
		msg.compact.join("<br>")
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorldCup2014</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render :partial => 'shared/header' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class='container-fluid'>
	<%= yield %>
</div>
</body>
</html>

app/views/shared/_header.html.erb
<div class="header row">
	<div class="col-md-8">
		<h3 class="text-muted">WC#Brazil2014</h3>
	</div>
	<div class="col-md-4">
		<div class="countdown"></div>
	</div>
</div>

app/views/tournaments/_match.html.erb
<%= content_tag :div, class: 'row match jumbotron', id: "match-#{match.id}" do -%>
	<div class "row match-container">
		<%= content_tag :div, class: 'col-md-5 team_a' do -%>
			<%= flag_tag match.team_a %>
			<strong><%= content_tag :span, match.team_a.name.upcase %></strong>
		<% end -%>

		<%= content_tag :div, class: 'time col-md-2' do-%>
			<% if match.future_match? %>		
				<%= content_tag :div, match.starting_time.strftime('%d|%m'), class: 'match-date' %>
				<%= content_tag :div, match.starting_time.strftime('%k:%M'), class: 'match-time' %>
	        <% else %>
	        	<%= content_tag :div, "#{match.team_a_score} : #{match.team_b_score}", class: 'match-score' %>
			<% end -%>
		<% end -%>

		<%= content_tag :div, class: 'team_b col-md-5' do -%>
			<%= flag_tag match.team_b %>
			<%= content_tag :div, class: 'text-right' do -%>
				<strong><%= match.team_b.name.upcase %> </strong>
			<% end -%>
		<% end -%>
	</div>
	<% if match.future_match? %>
		<div class="personal-msg row">
			<%= content_tag :div, class: 'col-md-12' do -%>
				<div><%= future_match_regular_bet_prospect match %></div>
				<div><%= future_match_custom_bet_prospect match %></div>
			<% end %>
		</div>
	<% end %>
<% end -%>

app/views/tournaments/_matches.html.erb
<h2> Next Matches </h2>
<%= render partial: 'match', collection: @next_matches %>

<h2> Past Matches </h2>
<%= render partial: 'match', collection: @past_matches %>

app/views/tournaments/_pick_a_team.html.erb
<%= simple_form_for(:bet, url: place_bet_tournament_path, remote: true) do |f| %>
  <%= f.input(:team_id, label: false, as: :radio_buttons, collection: @teams, required: true, label_method: lambda { |t| team_name_and_flag(t) }) %>
  <%= f.hidden_field :type_of_bet, value: @type_of_bet %>
  <%= f.button :submit, 'Next' %>
<% end %>

app/views/tournaments/_step_0.html.erb
<%= content_tag :div, class: 'bet-setup', id: "bet-setup-step-#{@step}" do -%>
	STEP 1: pick one amazing team team.
	<%= render partial: 'pick_a_team' %>
<%- end %>

app/views/tournaments/_step_1.html.erb
<%= content_tag :div, class: 'bet-setup', id: "bet-setup-step-#{@step}" do -%>
	STEP 2: pick a very good team.
	<%= render partial: 'pick_a_team' %>
<%- end %>

app/views/tournaments/_step_2.html.erb
<%= content_tag :div, class: 'bet-setup', id: "bet-setup-step-#{@step}" do -%>
	STEP 3: pick one ok team .
	<%= render partial: 'pick_a_team' %>
<%- end %>

app/views/tournaments/_step_3.html.erb
<%= content_tag :div, class: 'bet-setup', id: "bet-setup-step-#{@step}" do -%>
	STEP 4: pick some team o.o
	<%= render partial: 'pick_a_team' %>
<%- end %>

app/views/tournaments/_step_4.html.erb
<%= content_tag :div, class: 'bet-setup all-teams-radio', id: "bet-setup-step-#{@step}" do -%>
	<p>STEP 5: pick the team that you think will score the most goals (you get half a point for every goal)</p> 
	<div><%= render partial: 'pick_a_team' %></div>
<%- end %>

app/views/tournaments/_step_5.html.erb
<%= content_tag :div, class: 'bet-setup all-teams all-teams-radio', id: "bet-setup-step-#{@step}" do -%>
	<p>STEP 6: pick the team that will get the most goals scored to (you get half a point for every goal)</p>
	<%= render partial: 'pick_a_team' %>
<%- end %>

app/views/tournaments/_world_cup_development.html.erb
_

app/views/tournaments/new_bet.html.erb
<%= content_tag :div, class: "jumbotron bet_setup #{'all-teams' if @step > 3}" do -%>
	<div class='col-md-6'>
		<p class="header">Place your bet</p>
		<%= render partial: "step_#{@step}" %>
	</div>
	<div class='col-md-6 rules'>
		<%= render partial: "rules" %>
	</div>
<%- end %>

app/views/tournaments/new_bet.js.erb
$('.bet-setup').fadeOut(200, function(){

<% if @step == 4 %>
	$('.jumbotron').animate({height: "+=100px"}, {duration: 500, complete: function(){
		$('.bet-setup').html('<%=j render partial: "step_#{@step}"%>').fadeIn(200);
	}});
<% else %>
	$('.bet-setup').html('<%=j render partial: "step_#{@step}"%>').fadeIn(200);
<% end %>
});

app/views/tournaments/place_bet.js.erb
$('.bet-setup').replaceWith('<%=j render partial: "step_#{@step}"%>');

app/views/tournaments/show.js.erb
$('.main-container')
.html("<div class='col-md-9'><%=j render partial: 'matches'%></div>")
.append("<div class='col-md-3'><%=j render partial: 'user_rank'%></div>");